import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './Header'
import Footer from './Footer'
import Loader from './Loader'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'our first next app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loader/>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
